import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono, Figtree } from "next/font/google";

import "./globals.css";
import { auth } from "@/lib/auth";
import SiteHeader from "@/components/site-header";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  return (
    <html lang="en" className={figtree.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-7xl mx-auto px-4`}
      >
        <SiteHeader session={session} />

        {children}
      </body>
    </html>
  );
}
